### ISSUE TITLE
[Bug]: Time format bug

### ISSUE THREAD

**Issue by Rsose** [RafaelGB/obsidian-db-folder#713] opened 2023-01-01 13:05 UTC
### What happened?

A bug happened!
When I found out the latest version of DB folder, I found a bug that caused no recognize time. I hope you are able to find and fix  this bug.
![image](https://user-images.githubusercontent.com/51273534/210171186-d914f95e-ef76-429b-8a08-685dd1aad367.png)
![image](https://user-images.githubusercontent.com/51273534/210171198-39f5185e-1331-458e-9ad7-f98d5cc51bb3.png)
![image](https://user-images.githubusercontent.com/51273534/210171231-71c759df-4fbf-466c-ad99-05c618635eb3.png)
---
This is version 3.0.0 it works
![image](https://user-images.githubusercontent.com/51273534/210171323-0f866530-94d3-4acf-958b-3c3cd041b646.png)

Thanks
Waiting for areply

### What platform were you using?

Desktop

### Version of the plugin

3.1.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment] 2023-01-01 14:18
looks like the saved format is not correct

It requires a quote wrapping 

9:30 => "9:30" to be recognised 

if not the yaml can not be read


I will investigate the cause!

**Comment by Rsose** [comment] 2023-01-01 14:24
Still not working, the previous version can recognize whether there are quotation marks or not

**Comment by RafaelGB** [comment] 2023-01-01 14:25
: between text value on a yaml can break the file read. 


Let me investigate 😯

**Comment by RafaelGB** [comment] 2023-01-01 18:34
Commit 712549cb

As best option, I think the ISO format will cover all the cases and its more resilient

**Comment by Rsose** [comment] 2023-01-02 09:14
![image](https://user-images.githubusercontent.com/51273534/210212230-13f630b5-aecc-4542-a65f-3330ef94cce9.png)
After the metadata time format is set, it has returned to normal.

Version 3.0.0 there was no metadata time format so that's the reason it doesn't work into lastest version
Thanks I resolved the problem
Happy New 2023 RafaelGB

**Comment by RafaelGB** [comment] 2023-01-02 14:49
just wait until 3.2 version. It will be fixed for all the situations

**Closed** 2023-01-04 12:07 UTC
Labels: bug
