### ISSUE TITLE
[Bug]: Regarding the missing latitude and longitude after importing csv files

### ISSUE THREAD

**Issue by Rsose** [RafaelGB/obsidian-db-folder#799] opened 2023-02-01 16:33 UTC
### What happened?

Hi RafaelGB
I recently try to import the latitude and longitude information about the map into your plugin combine with another pluging called MapView, it uses Geographic coordinates to track pojnts in Obsidian
Because there are a lot of location information, I find them through Google Maps and add it to excel, and then import it into db-folder, otherwise it will be cumbersome to fill in all of them manually
I found that the data is perfect when exporting, but there are some problems when importing
Hope you can figure this out, because it's been bugging me.

**1-Screenshot :There is nothing wrong with manually adding information So there is no problem with exporting**
![image](https://user-images.githubusercontent.com/51273534/216100671-1767aa5a-6178-4998-ba88-3046aed35401.png)
---
**2-Screenshot: There is a data error after importing, or the location data separated by commas will be automatically added to the next metadata information(This case From location: to visit:)**
![image](https://user-images.githubusercontent.com/51273534/216100418-9b155cc3-d49e-414a-b511-b331f815d3c3.png)

Please you can compare it, the second screenshot is due to the yaml information error after importing.(longitude is moved to metadata Visit: ) quite strange

Waiting for a reply
Many thanks

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment] 2023-02-02 13:46
Hello @Rsose , We change the export library to paparse with the last version. Our intention is to use it with the import too for this cases

Thank for your report

**Comment by Rsose** [comment] 2023-02-02 17:24
Thanks for your effort, looking forward to a good result.

**Comment by RafaelGB** [comment] 2023-02-04 14:23
I could not reproduce your issue.

This was my testing
https://user-images.githubusercontent.com/11924043/216772686-e1c72d92-2ee7-444f-83de-818dae8e65c7.mov

Am I doing something different?

**Comment by Rsose** [comment] 2023-02-04 14:39
Hi RafaelGB
Here is CSV you can download it then import into OB 
I just tried it again and still have the same problem
[Location import issues.csv](https://github.com/RafaelGB/obsidian-db-folder/files/10608883/Location.import.issues.csv)

---
**Result after importing**
![image](https://user-images.githubusercontent.com/51273534/216773348-3de3471e-2ffa-4328-80a2-d54bc63e5e56.png)

**Comment by RafaelGB** [comment] 2023-02-04 17:50
I just import your file and all looks good to me. Maybe it was fixed with another change?

I will add the issue as won't fix for the next version, feel free to reopen it if the problem persist

**Comment by Rsose** [comment] 2023-02-04 19:54
Alright your system is Mac but I use windows 10
Maybe there will be no problem with the Mac system I dunno it will make difference between different computer system
Ok let's take a look at the next version

**Comment by RafaelGB** [comment] 2023-02-14 22:53
New version is ready, please let me know if the problem persist or was solved with another issue

**Closed** 2023-02-14 22:54 UTC
Labels: bug, wontfix

**Comment by Rsose** [comment] 2023-02-15 09:52
Thanks for solving the problem! It works now
I very appreciate it
