### ISSUE TITLE
[Bug]: New column metadata affects existing YAML block

### ISSUE THREAD

**Issue by martingarner** [RafaelGB/obsidian-db-folder#774] opened 2023-01-23 18:12 UTC
### Contact Details

martingarner@blueyonder.co.uk

### What happened?

Thanks for a very good add-in!
I *think* this is a bug, so please let me ask.

I added a column and new "tags" to it in a database.
I found the existing YAML headers in the notes (I'm a big user of these):
- got the new metadata from the new column name - all good
- now had a "---" immediately after it
- messed up the rest of the existing YAML block

It works well if your template already includes the metadata for the column for all notes.
But it messes up the YAML block for existing notes that do not have that metadata.

Could DB Folder check to see if it's inserting into an existing YAML block and not add the extra "---" marker half way through the block?

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment] 2023-01-23 18:19
Hello @martingarner ,
we are using the current Obsidian API to edit the frontmatter. It checks if another one exists.

Could you share some file of capture to reproduce the problem?

thanks for using the plugin 😄

**Comment by martingarner** [comment] 2023-01-23 18:52
Sure, thanks.
Here's the "before" YAML - an existing file for an organisation without the "Relevant_to" column
![image](https://user-images.githubusercontent.com/48418332/214124002-e329f57e-9281-4d32-a530-eb6d0a207d73.png)

Created a database using the tag #organisation
The organisation shows in the database, with new metadata added in the new "Relevant_to" column
![image](https://user-images.githubusercontent.com/48418332/214124421-6e308c48-143d-4290-b8a8-089197ac1cec.png)


And here's the "after" YAML
![image](https://user-images.githubusercontent.com/48418332/214124207-77aa8496-0376-44d5-879d-b5a036b41582.png)

Hope this helps.

**Comment by RafaelGB** [comment] 2023-01-23 18:58
https://user-images.githubusercontent.com/11924043/214125805-6e129a00-dc49-4357-9b15-31b5986dcf0a.mov

I thought it was due to the key that you have with a space but I have tried under the same conditions and it works

Obsidian interprets for some reason that this file does not have meta information. Any special character in between the beginning? does it happen with any file?

**Comment by martingarner** [comment] 2023-01-23 19:05
I'm not aware of any special characters.
I'd need to do a lot of testing to see all the conditions, but it's not 100%
Just tried another organisation file: before ..
![image](https://user-images.githubusercontent.com/48418332/214127104-f50b6d27-3b04-41a3-aba1-68640c409124.png)

And after ...
![image](https://user-images.githubusercontent.com/48418332/214127277-348b28fa-c517-4eaf-93fb-625afa9692bd.png)

I'm not clear what the difference is - why one works and the other does not.

**Comment by RafaelGB** [comment] 2023-01-23 19:10
I can not tell, maybe a space after `---` or something like that could affects the metadata format.

I will close this issue. If this problem happens again we can open a discussion and I will help you =)

**Closed by RafaelGB** 2023-01-23 19:10 UTC
Labels: bug, triage

**Comment by martingarner** [comment] 2023-01-23 21:28
Ok, thanks Rafael.
