### ISSUE TITLE
Failure to Edit Entry

### ISSUE THREAD

**Issue by plagalPatent** [RafaelGB/obsidian-db-folder#135] opened 2022-06-13 07:00 UTC
**Describe the bug**
Creating a new row for the Database poses no problem.
When I edit a row and then leave the pane and return, I lose all the new edited data (it reverts to original text).

**To Reproduce**
Create new row in DB.
Click to File and ensure it has been created.
Go back to DB and try to edit.
Click to File and see changes were not made.
Click to DB and see it has reverted to original.

**Expected behavior**
Edits should work

**Desktop (please complete the following information):**
 - Windows 10
 - v.1.7.0

**Additional context**
I do have Obsidian Sync enabled but I turned it off and issue still persists. 

Potentially the issue is the user (me) so let me know if I've missed something obvious.

**Comment by RafaelGB** [comment] 2022-06-13 07:13
Hello @plagalPatent 
Usually the edition problems are caused by some special character inside your frontmatter note that breaks the yaml. If your problem persist, please attach here your db and the note that cause the problem and will be reviewed as soon as possible.

**Comment by plagalPatent** [comment] 2022-06-13 08:23
Thanks @RafaelGB 
I have created a few DB and sometimes editing works, other times it does not.
See attached
[Book DB.md](https://github.com/RafaelGB/obsidian-db-folder/files/8889338/Book.DB.md)
.

**Comment by RafaelGB** [comment] 2022-06-30 10:37
Closing this issue like wont fix

**Closed by RafaelGB** 2022-06-30 10:37 UTC
Labels: wontfix
