### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#720] opened 2023-01-02 16:43 UTC
Received the follow error when trying to open any database. Have not altered any database file.
Have current Obsidian version and current DB Folder version.

<img width="235" alt="Screen Shot 2023-01-02 at 11 36 16" src="https://user-images.githubusercontent.com/106125987/210258565-5c0f8c66-a119-41bf-9c48-1702b43ef1fa.png">

File below for reference.
[TV Episode Release Database.md](https://github.com/RafaelGB/obsidian-db-folder/files/10332674/TV.Episode.Release.Database.md)

**Comment by RafaelGB** [comment] 2023-01-02 16:47
the plugin configuration is evolving with every version. If you dont have some property you will be involved about and the default value will be added

This notice message should appear just once

**Comment by Stilts15ak** [comment] 2023-01-02 16:49
The message appears every time the database file is clicked on and the database does not show.

**Comment by RafaelGB** [comment] 2023-01-02 16:54
I will check the problem of your db file.

Is it happens if you create a new one?

**Comment by Stilts15ak** [comment] 2023-01-02 17:10
This does not happen if a new one is created. The YAML keys missing are presented in a new database file, but not the previously created ones.

Note: The last time these databases where accessed was on a desktop Mac. I am currently on my MacBook Pro and am using iCloud Drive to sync files between devices. Not sure if that has any factor to it.

**Comment by RafaelGB** [comment] 2023-01-02 17:17
The plugin just check if those fields exists and add the default value. The cloud syncs should not be relevant

**Comment by Stilts15ak** [comment] 2023-01-02 17:18
That's what I thought. I've even tried putting those missing fields back into the md document, however it still won't open the database.

**Comment by RafaelGB** [comment] 2023-01-02 19:32
I was already able to test it and the problem is in the source of the database. Change `source_form_result: tv/tv-gen/tv_episode` to `source_form_result: "#tv/tv-gen/tv_episode"`

**Comment by Stilts15ak** [comment] 2023-01-02 20:30
That did it! Thanks!

**Closed** 2023-01-02 21:11 UTC
Labels: bug, wontfix
