### ISSUE TITLE
DB Folder Creating YAML Fields Without User Input

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#192] opened 2022-07-05 17:01 UTC
Hello!

I tried to add items to a database folder row, but DB Folder added stuff I didn't want it to. 

To reproduce:

1. Use the folder provided here: https://github.com/RafaelGB/obsidian-db-folder/issues/179
2. Create a new database
3. Delete the Column1
4. Add a "Year Created" number column
5. Add the number1902 to Bliss Classification

![image](https://user-images.githubusercontent.com/73113656/177379058-9f4adaa8-669a-4357-ab78-6858a553c14b.png)

the YAML on Bliss Classification will update to this

![image](https://user-images.githubusercontent.com/73113656/177379035-5a8b6ce1-e017-4820-a925-ba6999d68850.png)

```
---
Metadata: 
fileClass: KOS
KOSType:
 - Systems Integration
 - "[[500 - Research PKB & Methods/10. KOS/_todo/Classification/Classification.md|Classification]]"
Created: "2021-06-06 00:09"
aliases: 
tags: 
Year_Created: 1902
---
```

I don't know why the second item appeared in KOSType; it should just be:

```
---
Metadata:
fileClass: KOS
KOSType: Systems Integration
Created: 2021-06-06 00:09
aliases: []
tags: []
Year_Created: 1902
---
```

**Comment by brimwats** [comment] 2022-07-05 17:04
same thing happened for Dickinson Classification when I added 1938

![image](https://user-images.githubusercontent.com/73113656/177379875-f29eb964-ffda-4df8-92df-ed27139f1890.png)

**Comment by RafaelGB** [comment] 2022-07-05 17:27
Do you have another KOSType (as inline) in your file? dataview generates an array when 2 or more fields are repeated

**Comment by brimwats** [comment] 2022-07-05 17:32
no, here's the whole note. It's making a second entry because it's a [[]]

```md
---
Metadata: 
fileClass: KOS
KOSType:
 - Classification
 - "[[500 - Research PKB & Methods/10. KOS/_todo/Classification/Classification.md|Classification]]"
Created: "2022-07-01 23:19"
aliases: 
tags:
 - 🗄️/📇
Year_Created: 1938
---
# Dickinson Classification System for Music
BT⤴:: [[Classification System]] [[Music Metadata]]
↔RT:: [[KOS Case Studies]] 
NT⤵:: 
**Source Citation (if applicable):** 

---
**KOSType**:: [[Classification]]
*UsedBy*:: Music Libraries
*PurposeThemes*:: 
*Statistics*::  
**Authors**:: 
*DateCreated*:: 1938
*DecadeCreated*:: 1930s
*DatesUpdated*:: 
*DecadesUpdated*:: 
**RelatedKOS**:: 


--- 
## Notes
- The Dickinson classification scheme was originally published in 1938 by George Sherman Dickinson at Vassar College in New York State. The system was created to organize music scores in music libraries of various sizes and functions. Due to the system's intended flexibility, revisions appear to be left up to individual institutions, with no centralized governing committee. This led to the system losing popularity in the latter half of the twentieth century as standardized classification systems came into being and libraries began connecting in interlibrary coalitions (Lee, 2015). Though it never obtained a broad popularity there are universities scattered throughout the United States that continue to use the Dickinson system, or its most popular adaptation, the Vassar Columbia scheme.
- The Dickinson system is organized by instrumentation and size of ensemble with the first category, designated 0, set aside for miscellaneous items. Categories 1-6 cover works for solo instruments all the way up to orchestral works. Categories 7-9 cover vocal works, resetting to solo works and building to choral ensemble works and finally operas and ballets. Resources in these categories are further organized by composer, title, and edition (Bradley, 1972).
## Advantages
- The Dickinson scheme is so specialized that its only viable use is with large collections of music. By far the most common place for large collections of this kind is in college and universities with prominent schools of music or fine arts departments. Additionally, due to the flexible nature with which the system can be applied it would either need to be used by a library that had no intention of connecting with other institutions, or used in a system of libraries that all agreed on one way to apply the system.the 
## Disadvantages & Critiques
-  There are two noticeable issues with the system itself. First, the instruments listed as subcategories are all western instruments. Works from cultures outside the blanket of western art music are shelved with the existing instrument category they are most closely related to. The decision to relate other cultures to their counterpart in western music supports the eurocentric view of music held by most institutions in the US. 
- Second, the categories for vocal music are divided into sacred, secular, and folk music. The issue here is that the division is based on subject matter and style, where the rest of the system is divided by instrumentation.
## Sources
BRADLEY, C. (1972). The Dickinson Classification for Music. *Fontes Artis Musicae,* *19*(1/2), 13-22. Retrieved October 16, 2020, from [[http://www.jstor.org/stable/23505207]{.ul}](http://www.jstor.org/stable/23505207)

Columbia University. Library. Music library. (1955). Manual for the classification and cataloging of music scores (1955 revision). the \"vassar-columbia\" classification scheme integrated with the cataloging procedure manual of the columbia university music library, and the whole expanded and rev. by virginia G. haft, music scores cataloger. New York (State): Trustees of Columbia University, c1955

Dickinson, G. S., 1888-1964. (1938). Classification of musical compositions; a decimal-symbol system \[by\] george sherman dickinson. New York (State): Vassar college, 1938.

Lee, D. (2015). Consumption, Criticism and Wirkung: Reception-Infused Analysis of Classification Schemes. *Knowledge Organization*, *42*(7), 508--521. https://doi-org.ezproxy.library.ubc.ca/10.5771/0943-7444-2015-7-508



```

**Comment by brimwats** [comment] 2022-07-05 17:33
but I didn't add a KOSType column so I wouldn't have expected DB folder to handle it. i can understand how it picked it up though, but why didn't it also pick up DateCreated DecadeCreated UsedBy? (it would save me time if it created those columns!)

**Comment by RafaelGB** [comment] 2022-07-05 17:36
Even if you do not add the columns, the plugin check all fields and rewrite them in the same order. Have to test this behaviour

**Comment by RafaelGB** [comment] 2022-07-05 17:37
Inline fields with * or ** wrap its not supported yet. I guess that's the reason

**Comment by brimwats** [comment] 2022-07-05 17:38
oh fascinating. would it work in a callout? I've been considering editing mine to callouts anyhow

**Comment by RafaelGB** [comment] 2022-07-05 17:41
```ts
const inlineFieldRegex = new RegExp(`(^${columnId}[:]{2})+(.*$)`, 'gm');
```

We have to improve this regex to support it

**Comment by RafaelGB** [comment] 2022-07-25 14:26
## How to reproduce:
- same field key with frontmatter and inline
- Edit any cell
dataview groups in lists those repeated parameters, so  **KOSType** will be modified with the actual dataview array.

There is no way to differentiate if the array is part of several parameters or is an array created by the user with the actual dataview api version.

## How to resolve this issue?
Obtain vía File of Obsidian API the actual Frontmatter cache instead of vía Dataview

## Problems with change
There is no way yet to differentiate inline fields grouped into an array



I will think about the solution, but it will not be available with the release of 2.0.0 as it is an important change in the save mode

**Comment by ryanwwest** [comment] 2022-09-16 04:32
I've found a slight variation to this bug that could maybe be solved at the same time. I don't use YAML front matter fields, just Dataview fields, so I do not have the `---` markers that start and end the front matter block at the top of every note. However, this plugin ends up automatically adding two sets of markers if I make a change, even though they are unnecessary since only Dataview is required. I'd prefer to not have to have them taking up space.

Of course, this becomes more complicated if you add new fields, as you must now choose whether they appear as YAML front matter or inline Dataview fields. So that leaves the realm of 'bug' and goes into a new user setting. But I think the bug I mention doesn't have to apply to this.

**Comment by RafaelGB** [comment] 2022-09-16 07:22
Currently the plugin editing engine requires inserting these fields mandatorily. We will work so that in the future it automatically detects when it is not necessary and generates less noise for the user

**Comment by RafaelGB** [comment] 2022-10-17 12:16
With last versions I don't know if this problem still persist, the engine editor was quite improved
- inline now supports **
- yaml --- is not added if its empty

**Comment by RafaelGB** [comment] 2022-10-28 05:41
I will close this issue as wont fix

**Closed by RafaelGB** 2022-10-28 05:41 UTC
Labels: bug, wontfix
