### ISSUE TITLE
[Bug]: Table view hiding navbar

### ISSUE THREAD

**Issue by Alejandro-Stolz** [RafaelGB/obsidian-db-folder#625] opened 2022-11-23 17:18 UTC
### What happened?

The table hides the navbar when scrolling down the list.
My navbar looks like this:
![image](https://user-images.githubusercontent.com/73649874/203608563-ecbc4cb8-53fd-4e7e-8890-7057c43c47a2.png)
but when I scroll down, the content goes on top of the navbar:
![image](https://user-images.githubusercontent.com/73649874/203608532-0c3e876c-35b4-4064-a4f6-fc31a370e623.png)

I have fixed it using z-index and background-color: black
![image](https://user-images.githubusercontent.com/73649874/203608480-98d8ae91-4362-4cd5-980d-b5c9e1b463fc.png)
Surely there is a better way to do this, taking for example the default background color of the theme.
Probably not a bug, just enhancement but thanks in advance :) love your plugin
PD: Using Minimalist theme on the screenshots but happens on the Default theme too

### What platform were you using?

Desktop

### Version of the plugin

2.9.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment] 2022-11-23 22:07
Hi @Alejandro-Stolz ,
Looks like a css incompatibility with your theme. Which theme are you using?

**Comment by Alejandro-Stolz** [comment] 2022-11-24 09:15
I'm using Minimalist theme on the screenshots.

I've tried the following: switch to default theme + disable all plugins except dataview and DB Folder. It happens too. What I find strange is, that it only happens to the first column, the rest are visible but behind the header. I disabled also the only css-script I was using. I have tested this only on Windows, later today I can test it on linux if you haven't. 

Does it not happen to you? Then it would be very strange and I better check if it also happens on linux. Will keep you updated on that

**Comment by RafaelGB** [comment] 2022-11-24 09:33
With MacOS the issue is not reproduced and I am using Minimal Theme from Kepano & default one.

Also with Windows seems fine for me

**Comment by Alejandro-Stolz** [comment] 2022-11-24 09:41
I've continued testing and with the Default theme, it only happens with the first (sticky) column, the rest hide correcly. I'm going to continue looking into it, maybe try to find the classes that are being used in the theme and I'm going to update you on it.

**Comment by Alejandro-Stolz** [comment] 2022-11-24 10:05
So I looked in the theme .css file, and found some classes for the db folder. I don't know if the theme does include these or if the plugin adds these themselves. 
![image](https://user-images.githubusercontent.com/73649874/203755729-17d32abe-3909-4453-8417-585ba1b29a5e.png)

I changed that to this and it solved the problem for me.
```
.database-plugin__navbar {
	width: 100%;
	z-index: 3 !important;
	background-color: var(--background-primary);
}

.database-plugin__scroll-container,
.database-plugin__table {
  width: 100%;
}
```

**Comment by RafaelGB** [comment] 2022-11-24 10:11
The Theme is overwriting the css of the plugin with those lines then.

I currently working on a new design and offer a more configurable css for those plugins
https://github.com/RafaelGB/obsidian-db-folder/issues/577

With your snippet we can close this issue, thanks!

**Closed by RafaelGB** 2022-11-24 10:11 UTC
Labels: bug, Visual, external

**Comment by Alejandro-Stolz** [comment] 2022-11-24 10:25
Perfect! Thank you very much. Maybe the creator of the theme (kepano) can also improve the css in the theme a bit as he has done with these:
![image](https://user-images.githubusercontent.com/73649874/203760378-e5dbd418-7822-4f02-b5eb-78010fdc9d7d.png)
Thank you very much again for your time. This is really an outstanding plugin 😄

**Comment by Alejandro-Stolz** [comment] 2022-11-24 13:05
@RafaelGB another small visual improvement that could be made, as you are already working on something is making the outline show completely. At the moment with minimalist theme the outlines are sometimes hidden like this:
![image](https://user-images.githubusercontent.com/73649874/203791097-3e5ff42e-87df-41de-be98-2fd42766b062.png)
![image](https://user-images.githubusercontent.com/73649874/203791117-42ab3a37-7ca3-49e3-b991-ab0727fa3355.png)
![image](https://user-images.githubusercontent.com/73649874/203791153-21cfc7f2-7a81-4324-8d12-491544c346e1.png)
I have no idea what is causing this, but in the default theme, not surprisingly, this is not a problem. If I discover why I'll let you know. But surely something in the theme is overriding the css properties again. 
It only happens with the first row and column, the rest is fine.

**Comment by Alejandro-Stolz** [comment] 2022-11-24 13:15
Follow up: found the part in the css that affects this.
![image](https://user-images.githubusercontent.com/73649874/203793380-feb44ea7-c3b9-4105-9771-7323c534738a.png)

**Comment by Alejandro-Stolz** [comment] 2022-11-24 13:24
Commenting on the navbar topic: With the "Prism" theme it does not happen, but with several others I have the problem too.

**Comment by RafaelGB** [comment] 2022-11-24 13:36
yeah, a pending task is to make it easier for themes to work with dbfolder. I am not an expert in css but with future versions the plugin will improve in that aspect
