### ISSUE TITLE
[Bug]: Pagination buttons are inaccessible in mobile.

### ISSUE THREAD

**Issue by uroybd** [RafaelGB/obsidian-db-folder#688] opened 2022-12-23 16:03 UTC
### Contact Details

connect@utsob.me

### What happened?

Notice the pagination buttons at the bottom. They are hidden behind the bottom menu of Obsidian.

![Screenshot_2022-12-23-22-01-28-885_md obsidian](https://user-images.githubusercontent.com/4207230/209364501-b589b62b-5fb9-4d1e-8cba-eb75beca66ae.jpg)

### What platform were you using?

Mobile

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment] 2022-12-23 18:01
we have to support more kind of resolutions, thanks for the report !

**Comment by RafaelGB** [comment] 2022-12-26 15:19
You can create your own css snippet to support your resolution

I do not know the exact dimensions of your device so maybe you have to test some values like max height pixels or height percentage

This is my bet to fix it

```css
@media only screen and (max-height: 768px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 82%;
  }
}
```

**Comment by uroybd** [comment] 2022-12-27 06:19
> You can create your own css snippet to support your resolution
> 
> I do not know the exact dimensions of your device so maybe you have to test some values like max height pixels or height percentage
> 
> This is my bet to fix it
> 
> ```css
> @media only screen and (max-height: 768px) {
>   .database-plugin__scroll-container {
>     will-change: transform;
>     width: 100%;
>     height: 82%;
>   }
> }
> ```

I tried this. Didn't help since the pagination button is positioned absolutely at the bottom. Instead, it worked:

```css
.database-plugin__pagination {
    width: fit-content;
    height: 40px;
    list-style: none;
    /* bottom: 1em; */
    /* position: absolute; */
    /* right: 0; */
    /* margin: 0; */
    padding: 0 10px 0 0;
    display: flex;
    column-gap: 2px;
    margin-top: 1em;
    margin-left: auto;
}
```

A good thing about this approach is it will work in all breakpoints. Even in situations like this on a desktop where the status bar overlaps the pagination buttons:

<img width="759" alt="Screenshot 2022-12-27 at 12 18 29 PM" src="https://user-images.githubusercontent.com/4207230/209620696-004099c2-fc50-4b81-aa4f-d618cc099295.png">

**Comment by RafaelGB** [comment] 2022-12-27 08:13
I'm glad you were able to find a solution to your resolution.

For other features I was testing your snippet but it doesn't fit with most and is completely lost in case of activating the search bar.

`position: absolute` is a must

**Comment by uroybd** [comment] 2022-12-27 09:05
You can go for a flex-based solution though. The main container can be a column flex with the height set with calc (e.g. `calc(100vh - 50px)`, Then the table with `flex: 1` to take maximum available space, and pagination bar just after that, taking the necessary space.

**Comment by RafaelGB** [comment] 2022-12-27 10:23
the problem is Obsidian's own scroll. Being able to hide the search bar and for better control of the overflow, it would not be possible to use flex without having a second scroll bar on the right when we show the bar or the size of the pagination is greater than the default.

I will wait until the official 1.1 on Mobile, maybe we are testing different sources

**Comment by imeed166** [comment] 2023-01-06 09:09
### Another possible solution : 

You can provide 4 buttons (`>` `<` `<<` `>>`) in the **ribbon** for devices that don't have the **status bar** (phones). And hide these **ribbon** buttons on the other devices that have a **status bar** (desktop). 

And if this solution works for you, then you can also transfer the pagination buttons to the **status bar** on desktop.

**Comment by RafaelGB** [comment] 2023-01-06 09:44
Once the Obsidian 1.1 is released on mobiles, I think this issue will be fixed with a css improvement of 3.1.0

**Comment by RafaelGB** [comment] 2023-01-10 18:22
Could you check if this issue was resolved with 3.2.3? I am not able to test it well on android

**Comment by uroybd** [comment] 2023-01-10 18:24
> Could you check if this issue was resolved with 3.2.3? I am not able to test it well on android

I surely will once I get the next update of Obsidian.

**Comment by RafaelGB** [comment] 2023-01-10 18:26
With v3.2.3 of the plugin the mobile version is available again

**Comment by uroybd** [comment] 2023-01-10 18:52
No, this issue persists, so does the weird formatting issue which may rewrite my files with formatted text in desktop again.

![Screenshot_2023-01-11-00-49-43-285_md obsidian](https://user-images.githubusercontent.com/4207230/211637086-aa27d664-0ecd-4f0b-9194-88fd8b4c4590.jpg)

**Comment by RafaelGB** [comment] 2023-01-10 18:59
I will work on this visual issue then


about the rewrite thing should not be happening with this flag https://github.com/RafaelGB/obsidian-db-folder/blob/e21e8da5d034c30140a4efd6d031fe60350b0fca/src/components/cellTypes/FormulaCell.tsx#L58

**Comment by uroybd** [comment] 2023-01-10 20:05
> I will work on this visual issue then
> 
> 
> about the rewrite thing should not be happening with this flag https://github.com/RafaelGB/obsidian-db-folder/blob/e21e8da5d034c30140a4efd6d031fe60350b0fca/src/components/cellTypes/FormulaCell.tsx#L58

The rewrite might not happen. However, the formula is running 4 times recursively. Weird.

**Comment by uroybd** [comment] 2023-01-10 20:10
It seems like links are not being rendered anymore.

**Comment by uroybd** [comment] 2023-01-10 20:21
Wikilinks in simplest form works. But wikilinks with custom text don't.

**Comment by RafaelGB** [comment] 2023-01-10 20:36
thanks for the testing, I will open an issue your your comment

**Comment by RafaelGB** [comment] 2023-01-15 20:17
Commit 8fd0f600

Could a possible solution. Now just for mobile devices you can do an extra bottom scroll to show the pagination

**Closed** 2023-01-24 21:40 UTC
Labels: bug
