### ISSUE TITLE
database settings menu disappear in 1.8.2

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#193] opened 2022-07-05 17:08 UTC
**Describe the bug**
I can't access the database settings from the menu after updating to 1.8.2

**To Reproduce**
update to 1.8.2

**Expected behavior**
menu should appear like the last versions

**Screenshots**

https://user-images.githubusercontent.com/38974541/177380133-0af42e8a-c614-41e8-936a-020a73299a7b.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Obsidian 0.14.5

**Comment by RafaelGB** [comment] 2022-07-05 17:33
https://user-images.githubusercontent.com/11924043/177383645-a5a8cd54-5257-4c58-adc0-21bdc3f03b08.mov

I can't reproduce the issue. Maybe an incompatibility with another thing?

**Comment by imeed166** [comment] 2022-07-05 18:08
Tried with a clean vault and I have the same behavior, dataview 0.5.40

https://user-images.githubusercontent.com/38974541/177389336-9d7187e6-98dd-4891-ad4f-13de8dd147c9.mov

**Comment by jcdeichmann** [comment] 2022-07-06 00:47
Heads up that I just installed `obsidian-db-folder` for the first time and I can't see db settings in the menu either.

OS: macOS 11.1
Obsidian: 0.14.15
Dataview: 0.5.40
DB Folder: 1.8.2

**Comment by RafaelGB** [comment] 2022-07-06 07:07
I managed to reproduce it. I'll see how to fix it this afternoon

**Comment by imeed166** [comment] 2022-07-06 18:34
Okay, thank you for explaining

**Comment by RafaelGB** [comment] 2022-07-12 19:02
obsidian 15.6 is public no. Closing this one

**Closed** 2022-07-12 19:02 UTC
Labels: bug, wontfix
