### ISSUE TITLE
Cannot drag/drop files after viewing the database

### ISSUE THREAD

**Issue by Mazarkus** [RafaelGB/obsidian-db-folder#239] opened 2022-08-04 02:25 UTC
**Describe the bug**
After creating a new database file to mess around, I discovered I could no longer drag-drop files within my vault file structure.  I was able to recover the capability by restarting the program, but as soon as I viewed a database (even when only in markdown), I was then unable to move files around.  

**To Reproduce**
1. Make sure Dataview and DB Folder are installed and enabled
2. open a database note
3. attempt to move a file to another folder (doesn't matter which file)
4. open the file (so the database note isn't active)
5. restart obsidian
6. attempt to move the file (should be successful now)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.1

**Additional context**
I have attempted to disable all of my other plugins, and with only "Dataview" and "DB Folder" enabled, I still have the problem
If all plugins are disabled, I can successfully move files even after viewing the database note (now exclusively in markdown)

**Comment by RafaelGB** [comment] 2022-08-04 06:01
I will investigate the cause. Thanks for the report!

**Comment by RafaelGB** [comment] 2022-08-04 06:41
Something inside this react-dnd is affecting the DnD of Obsidian. Not not if Obsidian use the same library and exist an incompatibility because we are doing nothing special here, its the official example of react-dnd documentation
```ts
const [{ isDragging, handlerId }, drag] = useDrag(
    () => ({
      type: DnDConfiguration.DRAG_TYPE,
      item: { id, originalIndex },
      collect: (monitor) => ({
        handlerId: monitor.getHandlerId(),
        isDragging: monitor.isDragging(),
      }),
      end: (item, monitor) => {
        const { id: droppedId, originalIndex } = item;
        const didDrop = monitor.didDrop();
        if (!didDrop) {
          moveColumn(originalIndex, droppedId);
        }
      },
    }),
    [id, originalIndex, findColumn]
  );

  const [, drop] = useDrop(
    () => ({
      accept: DnDConfiguration.DRAG_TYPE,
      hover({ id: draggedId }: DragItem) {
        if (draggedId !== id) {
          const { index: overIndex } = findColumn(id);
          moveColumn(overIndex, draggedId);
        }
      },
    }),
    [findColumn]
  );
```

Still Working on it

**Comment by RafaelGB** [comment] 2022-08-04 07:11
Maybe relation with https://github.com/react-dnd/react-dnd/issues/3304

**Comment by Mazarkus** [comment] 2022-08-06 14:21
Thanks for looking into this! I'm just glad to know I wasn't imagining things.

**Comment by RafaelGB** [comment] 2022-08-09 14:24
I will reopen this because still being a problem. Not for DnD of Obsidian but with the plugin itself.

The solution should be with the context property but not the way I expose

**Comment by RafaelGB** [comment] 2022-08-18 14:38
Until find a way to fix this, I will enable a configuration to can use the actual DnD. You can disable it if you want
<img width="842" alt="Screenshot 2022-08-18 at 16 37 24" src="https://user-images.githubusercontent.com/11924043/185422723-cf14aa2e-7bf8-4781-8104-8f4cb547b432.png">

**Comment by RafaelGB** [comment] 2022-08-18 14:41
The most promising way is this example using frames (different context of Obsidian by force)

https://react-dnd.github.io/react-dnd/examples/dustbin/iframe

Dnd does not break the app but works with an iframe requires several refactors and  I am not sure if is a good idea

**Comment by RafaelGB** [comment] 2022-08-31 11:32
https://github.com/atlassian/react-beautiful-dnd just update and it is now compatible with react 18! A solid fix for this issue maybe?

**Comment by RafaelGB** [comment] 2022-09-01 19:34
react-beautiful-dnd breaks the resize, so is not worth it

**Comment by RafaelGB** [comment] 2022-09-08 22:22
fixed thanks to this tutorial =)

https://web.dev/drag-and-drop/

ready for the next version

**Closed** 2022-09-10 17:05 UTC
Labels: bug, reopen, external

**Comment by Mazarkus** [comment] 2022-09-10 17:20
Seems to be working for me too, thanks for investigating!
