### ISSUE TITLE
[Bug]: Error during database creation 

### ISSUE THREAD

**Issue by gbeyrend** [RafaelGB/obsidian-db-folder#826] opened 2023-02-17 11:06 UTC
### Contact Details

guillaume.beyrend@gmail.com

### What happened?

While trying to create a database, I got this error:
Error creating database "" : TypeError: kr.getDataviewAPI(....).isDataArray is not a function 
No database is created. 

### What platform were you using?

Desktop

### Version of the plugin

3.3.1

### Relevant log output

```shell
app.js:1 Error: [CM6] tree.iterate has changed syntax.
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at app.js:1:1045852
    at e.iterate (app.js:1:501709)
    at e.Uc.iterate (app.js:1:1046086)
    at Object.build (plugin:obsidian-admonition:766:2080)
    at Object.update (plugin:obsidian-admonition:766:1896)
    at e.update (app.js:1:350332)
    at e.updatePlugins (app.js:1:440837)
    at e.update (app.js:1:439009)
    at e._dispatch (app.js:1:436036)
    at e.dispatch (app.js:1:437814)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment] 2023-02-17 20:13
Hello @gbeyrend ,
It looks like a problem with obsidian-admonition in base of the logs you shared. Could you try to disable it and try to create another db?

**Comment by gbeyrend** [comment] 2023-02-18 07:08
Thank you very much for your swift answer. I tried it and it didn't work. It. was misleading because I actually didn't paste the whole log. Here is the correct log :

ParseService.ts:59 Uncaught (in promise) TypeError: kr.getDataviewAPI(...).isDataArray is not a function
    at Tm.parseDataArray (ParseService.ts:59:12)
    at Tm.parseLiteral (ParseService.ts:29:9)
    at x2.parseValueToThuthyYaml (databaseHelperCreationModal.ts:250:29)
    at x2.eval (databaseHelperCreationModal.ts:61:50)
    at Generator.next (<anonymous>)
    at eval (Constants.ts:14:11)
    at new Promise (<anonymous>)
    at a (plugin:dbfolder:1:697)
    at eval (databaseHelperCreationModal.ts:60:70)
    at t.onChanged (app.js:1:1140355)

**Comment by RafaelGB** [comment] 2023-02-24 21:52
`kr.getDataviewAPI(...).isDataArray is not a function` it's a dataview tool.
 I want to resolve your problem but I can not relate the bug
 
 The lines:
 https://github.com/RafaelGB/obsidian-db-folder/blob/7cf3d16e1da05820a3beaf11566692e6ffd29d7e/src/services/ParseService.ts#L45

**Comment by gbeyrend** [comment] 2023-02-25 18:49
Neither do I, even if I am more an R user. I don't see what I am doing wrong, I have the same version as others, no conflicts with other plugins. Maybe, if possible, would you have 15 minutes one day to check with me remotely in private @RafaelGB ? I don't see the reason why the plugin is not working for me.

**Comment by ghweili** [comment] 2023-03-12 15:47
I got the same error; I'm using the latest software and plugins: 
obsidian v1.1.16
dataview 0.4.21 (just updated it today)

From the error, it seems that it has something to do with Dataview,  seems that it did not get its parameter? It's worth mentioning that I also fail to use MetadataMenu 0.4.21 properly, a plugin that I just tried out today, which relies on dataview. This plugin tells me "plugin is not a valid fileClass" when I follow the tutorial.

**Comment by ghweili** [comment] 2023-03-12 15:53
I tried creating a database by right-click on a folder and choosing "new database folder", then a new page including the following error information shows up:
![image](https://user-images.githubusercontent.com/33361275/224556277-428ed72e-8fd0-42ae-b596-59184b2c355d.png)

**Comment by ghweili** [comment] 2023-03-13 03:16
Update: I installed the latest mobile version on android, then the database file can be created properly, and I can add rows to create files; however, seems that I can't add column, even though a message showing that it has been created successfully, I can't see the column appearing in the table. Moreover, if I try to type something in the a cell within the table, the same error message as on the desktop version appears.  

FYI, the vault folder on the android was copied from my desktop.

**Comment by ghweili** [comment] 2023-03-14 14:18
I saw more bugs here; for example, if I use "Tag" column in the clean new vault, I can type arbiratry string to create new tags, but in my previous vault, typing arbitrary strings only lead to "no options"

![image](https://user-images.githubusercontent.com/33361275/225029917-ac0528a8-ff00-4bb7-a43b-4a21c1ffac1f.png)

**Comment by ghweili** [comment] 2023-03-14 16:03
I'm wrong in saying that the above bug does not appear in a new vault; however, I found a solution to this problem, though I believe that there still might be a bug here. Please see the relevant post: 

https://github.com/RafaelGB/obsidian-db-folder/issues/850#issue-1623788020

**Comment by RafaelGB** [comment] 2023-03-16 06:10
I will create a custom isDataArray function to control this kind of error.

I'm sorry for the delay in responding, I moved house

**Comment by ghweili** [comment] 2023-03-16 06:13
as I said in the previous reply， this bug disappears after I uninstall dataview totally and reinstall it, though I found another relevant bug. Please see #850

**Comment by ghweili** [comment] 2023-03-16 06:15
however, the file icon issue persists in my vault, though this issue does not occur in a clean new vault. 

![image](https://user-images.githubusercontent.com/33361275/225531005-6e7c6071-2845-4f38-9022-09d2d395c49a.png)

**Comment by ghweili** [comment] 2023-03-16 06:20
to summarize, the dataview issue disappears after I uninstall dataview and install it again, though the icon issue as shown in the previous reply can occur in my previous vault, though it does not appear in a clean new vault.

 BTW, I found that I'm not the only one that suffers of the icon issue; I saw a tutorial video on db-folder on internet, and I  notice that the icon issue also appears in that tutorial video, though the poster didn't realize this as a bug. 

The second relevant issue here is the #850, which is associated with creating and using tags in a database file.

**Comment by RafaelGB** [comment] 2023-03-16 06:26
this issue and the control of the dataArray will be controlled with #850 , about the icon problem will be investigate independently, thanks for your testing, I really appreciate it

**Closed** 2023-03-16 06:27 UTC
Labels: bug, wontfix, external

**Comment by RafaelGB** [comment] 2023-03-20 21:56
Can you share a zip with your .obsidian folder to reproduce the problem? without debug it could be difficult to find the source of this mysterious problem

**Comment by ghweili** [comment] 2023-03-21 07:55
[plugins.zip](https://github.com/RafaelGB/obsidian-db-folder/files/11025873/plugins.zip)

[plugins2.zip](https://github.com/RafaelGB/obsidian-db-folder/files/11025895/plugins2.zip)


Above are the plugin files within the plugin folder of the new vault, which is created upon copying those within my previous vault into this new vault (tha latter has dataview and dbfoler installed properly).  Of course,  I didn't copy the dataview and dbfolder during the above operation).  

Notice that, the new vault (with dataview and dbfolder installed properly) worked properly at first,  but after this paste and restart the vault (I noticed that the newly imported plugins are all disabled by default, which I didn't touch),  the previous rows within a database file got lost, and it reports the following error when I create  a new row: 

 
![image](https://user-images.githubusercontent.com/33361275/226546411-46b2ec88-7511-4b62-9a04-44af6c0a55ec.png)


After I delete those newly pasted plugin folders and restart the vault, the missing rows come back, and I can continue creating new rows.
