### ISSUE TITLE
DB Folder does not respect case in YAML

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#269] opened 2022-08-18 20:44 UTC
I have YAML that reads something like

```
---
Metadata: 
Status: FirstPass
fileClass: KOS
KOSType: Classification
Created: 2022-07-14 17:00
aliases: [ANSCR]
tags: [🗄️/📇]
---
```

I made a new database folder. Selected columntype kostype (it was all lowercase) and refreshed the DB by hitting the button. I noticed one of my notes did not have KOSType: Classification so I added via DB Folder. However, the note i added it to had this added to the YAML

```
---
Metadata: 
aliases: 
Created: "2021-02-28 14:27:50"
kostype: Classification
---
```
`KOSType` should be `KOSType`, not `kostype`.

Resultingly, supercharged links does not apply the correct CSS to the file, as you can see here with the Chinese academyu of science classification:
![image](https://user-images.githubusercontent.com/73113656/185491326-78a89738-e60f-4e5a-8e3e-aa71b1dea897.png)

**Comment by RafaelGB** [comment] 2022-08-19 06:15
HI @brimwats 
For organization reasons, identifiers, if added from a template, are included in lowercase. In the future we can work on a less intrusive method, while you can modify that identifier within your database in markdown mode

modify for `key:` & `accesorKey:`

**Comment by brimwats** [comment] 2022-08-19 07:27
I didn't add it from a template, unless this is what you mean when you say template 
![image](https://user-images.githubusercontent.com/73113656/185566718-dc441de9-ad81-43b1-ae7c-4226d73498c0.png)

**Comment by RafaelGB** [comment] 2022-08-19 09:47
that option also use lowercase 😅

The reason is that a dataview query is used to find all those fields and returns every field duplicated with the first letter uppercase and lowercase, so the plugin cast all of them to lower then filter the duplicates

**Comment by brimwats** [comment] 2022-08-19 11:37
so you're saying that Dataview sees KOSTYPE kostype and KOSType as the same?

it might be my css then, which is currently like 


```
.data-link-icon[data-link-KOSType*="Classification" i]::before{
    content: "🗄️/📇";
    font-size: smaller;
}
```

maybe it's the * before "KOSType" that's making it tok strict? 🤔🤔🤔

**Comment by RafaelGB** [comment] 2022-08-19 12:50
Dataview returns **K**OSType & **k**OSType cause it was intended only for searches, but in our case affects the edition
 
The fact is the plugin must be able to display capitalization correctly. We will find a way to fix this in future versions

**Comment by brimwats** [comment] 2022-08-19 13:09
i see! thank you so much for all your hard work Rafael!

**Comment by toroworx** [comment] 2022-08-29 12:08
I would also love a fix, because this gets messy soon:

- My YAML data has camelCase keys (e.g. `redFruit`). 
- If I select an existing column to add, which is in smallcaps, it shows the correct value. 
- If I edit the value, db folder creates an extra `redfruit` field in the YAML data. The YAML data now contains `redFruit` and `redfruit`. This is unknown to the user unless you view the file's contents.

Thanks for the amazing plugin btw!

**Comment by RafaelGB** [comment] 2022-08-29 14:21
Fixed with adhoc code, but I open a discussion on dataview repo in case of exist an easy way to do it

https://github.com/blacksmithgu/obsidian-dataview/discussions/1376

**Closed** 2022-08-29 17:32 UTC
Labels: bug

**Comment by toroworx** [comment] 2022-08-29 18:32
Thanks for looking into this @RafaelGB. I think the best is to get this fixed in the Dataview plugin API.

There might be a workaround to get it properly working with this faulty API,  but in my opinion it's not the preferred way. A possible workaround might be to:

- Cast all results to lowercase to detect duplicates. Only do this in an internal function.
- If duplicates are found, use the version which has an uppercase letter in the key. This is very likely the correct version, else there wouldn't be a duplicate.

**Comment by RafaelGB** [comment] 2022-08-29 19:12
Yeah, I already leave a solution propose aplied in this plugin into dataview discussion
